require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayerdivsController do

  # This should return the minimal set of attributes required to create a valid
  # Playerdiv. As you add validations to Playerdiv, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all playerdivs as @playerdivs" do
      playerdiv = Playerdiv.create! valid_attributes
      get :index
      assigns(:playerdivs).should eq([playerdiv])
    end
  end

  describe "GET show" do
    it "assigns the requested playerdiv as @playerdiv" do
      playerdiv = Playerdiv.create! valid_attributes
      get :show, :id => playerdiv.id.to_s
      assigns(:playerdiv).should eq(playerdiv)
    end
  end

  describe "GET new" do
    it "assigns a new playerdiv as @playerdiv" do
      get :new
      assigns(:playerdiv).should be_a_new(Playerdiv)
    end
  end

  describe "GET edit" do
    it "assigns the requested playerdiv as @playerdiv" do
      playerdiv = Playerdiv.create! valid_attributes
      get :edit, :id => playerdiv.id.to_s
      assigns(:playerdiv).should eq(playerdiv)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Playerdiv" do
        expect {
          post :create, :playerdiv => valid_attributes
        }.to change(Playerdiv, :count).by(1)
      end

      it "assigns a newly created playerdiv as @playerdiv" do
        post :create, :playerdiv => valid_attributes
        assigns(:playerdiv).should be_a(Playerdiv)
        assigns(:playerdiv).should be_persisted
      end

      it "redirects to the created playerdiv" do
        post :create, :playerdiv => valid_attributes
        response.should redirect_to(Playerdiv.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved playerdiv as @playerdiv" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playerdiv.any_instance.stub(:save).and_return(false)
        post :create, :playerdiv => {}
        assigns(:playerdiv).should be_a_new(Playerdiv)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playerdiv.any_instance.stub(:save).and_return(false)
        post :create, :playerdiv => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested playerdiv" do
        playerdiv = Playerdiv.create! valid_attributes
        # Assuming there are no other playerdivs in the database, this
        # specifies that the Playerdiv created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Playerdiv.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => playerdiv.id, :playerdiv => {'these' => 'params'}
      end

      it "assigns the requested playerdiv as @playerdiv" do
        playerdiv = Playerdiv.create! valid_attributes
        put :update, :id => playerdiv.id, :playerdiv => valid_attributes
        assigns(:playerdiv).should eq(playerdiv)
      end

      it "redirects to the playerdiv" do
        playerdiv = Playerdiv.create! valid_attributes
        put :update, :id => playerdiv.id, :playerdiv => valid_attributes
        response.should redirect_to(playerdiv)
      end
    end

    describe "with invalid params" do
      it "assigns the playerdiv as @playerdiv" do
        playerdiv = Playerdiv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playerdiv.any_instance.stub(:save).and_return(false)
        put :update, :id => playerdiv.id.to_s, :playerdiv => {}
        assigns(:playerdiv).should eq(playerdiv)
      end

      it "re-renders the 'edit' template" do
        playerdiv = Playerdiv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playerdiv.any_instance.stub(:save).and_return(false)
        put :update, :id => playerdiv.id.to_s, :playerdiv => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested playerdiv" do
      playerdiv = Playerdiv.create! valid_attributes
      expect {
        delete :destroy, :id => playerdiv.id.to_s
      }.to change(Playerdiv, :count).by(-1)
    end

    it "redirects to the playerdivs list" do
      playerdiv = Playerdiv.create! valid_attributes
      delete :destroy, :id => playerdiv.id.to_s
      response.should redirect_to(playerdivs_url)
    end
  end

end
